# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building TomcatMavenApp"
      displayName: 'Build Application'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - script: |
        echo "Starting Deployment"
        echo "Deploying TomcatMavenApp"
        echo "Deployment Successful"
      displayName: 'Deploy Application'
